export type CatalogCategory =
  | 'all'
  | 'documents'
  | 'pdf_tools'
  | 'images'
  | 'image_to_pdf'
  | 'pdf_to_image'
  | 'spreadsheets'
  | 'presentations'
  | 'text_code'
  | 'data'
  | 'web'
  | 'ebooks'
  | 'archives'
  | 'vector'
  | 'utilities';

export interface ConverterTool {
  id: string;
  slug: string;
  title: string;
  shortDescription: string;
  category: CatalogCategory;
  categoryLabel: string;
  inputFormats: string[];
  outputFormats: string[];
  status: 'supported' | 'coming_soon';
  popular?: boolean;
  recentlyAdded?: boolean;
  iconName: string;
  features: string[];
  options?: {
    quality?: boolean;
    dpi?: boolean;
    pageSize?: boolean;
    orientation?: boolean;
    lineNumbers?: boolean;
    syntaxHighlighting?: boolean;
  };
}

export const CATEGORY_FILTERS: { id: CatalogCategory; label: string; icon: string }[] = [
  { id: 'all', label: 'All Converters', icon: 'grid' },
  { id: 'popular' as any, label: 'Popular Tools', icon: 'star' },
  { id: 'documents', label: 'Documents', icon: 'file-text' },
  { id: 'pdf_tools', label: 'PDF Tools', icon: 'pdf' },
  { id: 'images', label: 'Images', icon: 'image' },
  { id: 'image_to_pdf', label: 'Image to PDF', icon: 'images' },
  { id: 'pdf_to_image', label: 'PDF to Image', icon: 'camera' },
  { id: 'spreadsheets', label: 'Spreadsheets', icon: 'table' },
  { id: 'presentations', label: 'Presentations', icon: 'presentation' },
  { id: 'text_code', label: 'Text & Code', icon: 'code' },
  { id: 'data', label: 'Data Files', icon: 'database' },
  { id: 'web', label: 'Web Files', icon: 'globe' },
  { id: 'ebooks', label: 'Ebooks', icon: 'book' },
  { id: 'archives', label: 'Archives', icon: 'archive' },
  { id: 'vector', label: 'Vector Graphics', icon: 'pen-tool' },
  { id: 'utilities', label: 'Utilities', icon: 'zap' },
];

export const CONVERTER_TOOLS: ConverterTool[] = [
  // Popular / Core Tools
  {
    id: 'universal-converter',
    slug: 'universal-converter',
    title: 'Universal Auto-Converter',
    shortDescription: 'Upload any file — automatic magic-byte file detection and conversion to PDF, JPG, or PNG.',
    category: 'utilities',
    categoryLabel: 'Utilities',
    inputFormats: ['ANY'],
    outputFormats: ['pdf', 'jpg', 'png'],
    status: 'supported',
    popular: true,
    recentlyAdded: true,
    iconName: 'zap',
    features: ['Magic-byte file detection', 'Batch file support', 'Automatic format matching', 'High-speed processing'],
  },
  {
    id: 'file-analyzer',
    slug: 'analyzer',
    title: 'File Analyzer & Inspector',
    shortDescription: 'Inspect any file to reveal true magic-byte signature, MIME type, dimensions, and hidden file identity.',
    category: 'utilities',
    categoryLabel: 'Utilities',
    inputFormats: ['ANY'],
    outputFormats: ['INSPECT'],
    status: 'supported',
    popular: true,
    recentlyAdded: true,
    iconName: 'search',
    features: ['Magic-byte signature check', 'True MIME classification', 'Dimensions & size analysis', 'Misnamed file identification'],
  },
  {
    id: 'photo-print-studio',
    slug: 'photo-print',
    title: 'Photo Printout & Studio Editor',
    shortDescription: 'Upload photo, position on realistic white paper (A4, 4×6″, Passport sheet), edit with Photoshop adjustments, and print at 300 DPI.',
    category: 'images',
    categoryLabel: 'Images',
    inputFormats: ['jpg', 'png', 'webp', 'avif', 'bmp', 'tiff'],
    outputFormats: ['print', 'pdf', 'jpg'],
    status: 'supported',
    popular: true,
    recentlyAdded: true,
    iconName: 'printer',
    features: [
      'Realistic White Paper Sheet',
      'Passport 8-Pack with Cut Lines',
      'Photoshop Light & Color Adjustments',
      '300 DPI Print & PDF Output',
    ],
  },
  {
    id: 'png-to-jpg',
    slug: 'png-to-jpg',
    title: 'PNG to JPG Converter',
    shortDescription: 'Convert PNG images to crisp high-quality JPG files with transparent background flattening.',
    category: 'images',
    categoryLabel: 'Images',
    inputFormats: ['png'],
    outputFormats: ['jpg'],
    status: 'supported',
    popular: true,
    iconName: 'image',
    features: ['90+ Quality presets', 'White alpha flattening', 'Lossless Sharp engine', 'Batch processing'],
    options: { quality: true },
  },
  {
    id: 'jpg-to-png',
    slug: 'jpg-to-png',
    title: 'JPG to PNG Converter',
    shortDescription: 'Convert JPG photos to PNG format for lossless editing and transparent support.',
    category: 'images',
    categoryLabel: 'Images',
    inputFormats: ['jpg', 'jpeg'],
    outputFormats: ['png'],
    status: 'supported',
    popular: true,
    iconName: 'image',
    features: ['Lossless compression', 'PNG 24-bit color', 'Sharp libvips rendering'],
  },
  {
    id: 'pdf-to-jpg',
    slug: 'pdf-to-jpg',
    title: 'PDF to JPG Converter',
    shortDescription: 'Convert PDF document pages into high-resolution JPG images page by page.',
    category: 'pdf_to_image',
    categoryLabel: 'PDF to Image',
    inputFormats: ['pdf'],
    outputFormats: ['jpg'],
    status: 'supported',
    popular: true,
    iconName: 'camera',
    features: ['Multi-page extraction', 'Custom DPI selection', 'ZIP archive download', 'Page preview'],
    options: { dpi: true, quality: true },
  },
  {
    id: 'pdf-to-png',
    slug: 'pdf-to-png',
    title: 'PDF to PNG Converter',
    shortDescription: 'Convert PDF document pages into crisp lossless PNG images.',
    category: 'pdf_to_image',
    categoryLabel: 'PDF to Image',
    inputFormats: ['pdf'],
    outputFormats: ['png'],
    status: 'supported',
    popular: true,
    iconName: 'camera',
    features: ['Full page rendering', 'High DPI resolution', 'ZIP download', 'Transparent background support'],
    options: { dpi: true },
  },
  {
    id: 'docx-to-pdf',
    slug: 'docx-to-pdf',
    title: 'DOCX to PDF Converter',
    shortDescription: 'Convert Microsoft Word documents (DOCX/DOC) to professional PDF documents.',
    category: 'documents',
    categoryLabel: 'Documents',
    inputFormats: ['docx', 'doc', 'odt', 'rtf'],
    outputFormats: ['pdf'],
    status: 'supported',
    popular: true,
    iconName: 'file-text',
    features: ['Layout preservation', 'Font embedding', 'Table & image rendering', 'LibreOffice engine'],
    options: { pageSize: true, orientation: true },
  },
  {
    id: 'xlsx-to-pdf',
    slug: 'xlsx-to-pdf',
    title: 'XLSX to PDF Converter',
    shortDescription: 'Convert Excel spreadsheets (XLSX/XLS/CSV) to clean paginated PDF tables.',
    category: 'spreadsheets',
    categoryLabel: 'Spreadsheets',
    inputFormats: ['xlsx', 'xls', 'ods', 'csv'],
    outputFormats: ['pdf'],
    status: 'supported',
    popular: true,
    iconName: 'table',
    features: ['Grid line alignment', 'Header row repeating', 'Landscape auto-fit', 'Multi-sheet rendering'],
    options: { pageSize: true, orientation: true },
  },
  {
    id: 'pptx-to-pdf',
    slug: 'pptx-to-pdf',
    title: 'PPTX to PDF Converter',
    shortDescription: 'Convert PowerPoint presentations (PPTX/PPT) to multi-page PDF documents.',
    category: 'presentations',
    categoryLabel: 'Presentations',
    inputFormats: ['pptx', 'ppt', 'odp'],
    outputFormats: ['pdf'],
    status: 'supported',
    popular: true,
    iconName: 'presentation',
    features: ['Slide aspect ratio preservation', 'Vector shapes rendering', 'Full color background preservation'],
  },
  {
    id: 'jpg-to-pdf',
    slug: 'jpg-to-pdf',
    title: 'JPG to PDF Converter',
    shortDescription: 'Convert JPG & JPEG images into a formatted single or multi-page PDF document.',
    category: 'image_to_pdf',
    categoryLabel: 'Image to PDF',
    inputFormats: ['jpg', 'jpeg', 'png', 'webp', 'bmp', 'tiff'],
    outputFormats: ['pdf'],
    status: 'supported',
    popular: true,
    iconName: 'images',
    features: ['A4 auto-scaling', 'Margin controls', 'Multi-image combining', 'Aspect ratio locking'],
    options: { pageSize: true, orientation: true },
  },
  {
    id: 'json-to-pdf',
    slug: 'json-to-pdf',
    title: 'JSON to PDF Converter',
    shortDescription: 'Format and render raw JSON data into clean, readable PDF documents.',
    category: 'data',
    categoryLabel: 'Data Files',
    inputFormats: ['json'],
    outputFormats: ['pdf'],
    status: 'supported',
    popular: true,
    recentlyAdded: true,
    iconName: 'database',
    features: ['Pretty-print formatting', 'Syntax line wrapping', 'Courier monospace font', 'Page pagination'],
    options: { syntaxHighlighting: true, lineNumbers: true },
  },
  {
    id: 'csv-to-pdf',
    slug: 'csv-to-pdf',
    title: 'CSV to PDF Converter',
    shortDescription: 'Convert comma-separated data tables into paginated PDF documents.',
    category: 'spreadsheets',
    categoryLabel: 'Spreadsheets',
    inputFormats: ['csv', 'tsv'],
    outputFormats: ['pdf'],
    status: 'supported',
    popular: true,
    recentlyAdded: true,
    iconName: 'table',
    features: ['Row & column alignment', 'Courier font spacing', 'Landscape layout', 'Auto line-wrap'],
    options: { orientation: true },
  },
  {
    id: 'code-to-pdf',
    slug: 'code-to-pdf',
    title: 'Code to PDF Converter',
    shortDescription: 'Convert Python, JavaScript, TypeScript, C++, Java, SQL, and other source code files into styled PDF documents.',
    category: 'text_code',
    categoryLabel: 'Text & Code',
    inputFormats: ['py', 'js', 'ts', 'jsx', 'tsx', 'cpp', 'c', 'java', 'sql', 'html', 'css', 'json', 'md', 'txt'],
    outputFormats: ['pdf'],
    status: 'supported',
    popular: true,
    recentlyAdded: true,
    iconName: 'code',
    features: ['Multi-language syntax highlighting', 'Line numbering support', 'Monospace Courier font', 'Custom page orientation'],
    options: { lineNumbers: true, syntaxHighlighting: true, orientation: true },
  },
  {
    id: 'latex-to-pdf',
    slug: 'latex-to-pdf',
    title: 'LaTeX to PDF Studio & Compiler',
    shortDescription: 'Interactive Overleaf-style LaTeX editor, equation typesetter, and ATS resume compiler with live PDF preview.',
    category: 'text_code',
    categoryLabel: 'Text & Code',
    inputFormats: ['tex', 'latex'],
    outputFormats: ['pdf'],
    status: 'supported',
    popular: true,
    recentlyAdded: true,
    iconName: 'code',
    features: ['Overleaf split-editor', 'Live PDF recompiler', 'ATS 100% resume templates', 'Vector math typesetting'],
  },
  {
    id: 'html-to-pdf',
    slug: 'html-to-pdf',
    title: 'HTML to PDF Converter',
    shortDescription: 'Render HTML documents and web templates into styled PDF documents.',
    category: 'web',
    categoryLabel: 'Web Files',
    inputFormats: ['html', 'htm', 'xhtml'],
    outputFormats: ['pdf'],
    status: 'supported',
    popular: true,
    iconName: 'globe',
    features: ['DOM element rendering', 'CSS styling preservation', 'Safe local execution', 'Chromium engine'],
  },

  // Specialized & Additional Tools
  {
    id: 'webp-to-jpg',
    slug: 'webp-to-jpg',
    title: 'WebP to JPG Converter',
    shortDescription: 'Convert modern WebP web images into standard JPG images.',
    category: 'images',
    categoryLabel: 'Images',
    inputFormats: ['webp'],
    outputFormats: ['jpg', 'png'],
    status: 'supported',
    iconName: 'image',
    features: ['Sharp libvips rendering', 'Alpha flattening', 'High resolution retention'],
  },
  {
    id: 'gif-to-jpg',
    slug: 'gif-to-jpg',
    title: 'GIF to JPG Converter',
    shortDescription: 'Convert GIF images and animations to static high-quality JPG frames.',
    category: 'images',
    categoryLabel: 'Images',
    inputFormats: ['gif'],
    outputFormats: ['jpg', 'png'],
    status: 'supported',
    iconName: 'image',
    features: ['First-frame extraction', 'Color palette expansion', 'Instant conversion'],
  },
  {
    id: 'bmp-to-jpg',
    slug: 'bmp-to-jpg',
    title: 'BMP to JPG Converter',
    shortDescription: 'Convert uncompressed bitmap (BMP) graphics into compressed JPG images.',
    category: 'images',
    categoryLabel: 'Images',
    inputFormats: ['bmp'],
    outputFormats: ['jpg', 'png'],
    status: 'supported',
    iconName: 'image',
    features: ['Bitmap decoding', 'File size reduction up to 90%', 'Sharp optimization'],
  },
  {
    id: 'tiff-to-jpg',
    slug: 'tiff-to-jpg',
    title: 'TIFF to JPG Converter',
    shortDescription: 'Convert multi-page or high-res TIFF graphics into standard JPG images.',
    category: 'images',
    categoryLabel: 'Images',
    inputFormats: ['tiff', 'tif'],
    outputFormats: ['jpg', 'png'],
    status: 'supported',
    iconName: 'image',
    features: ['16-bit to 8-bit channel mapping', 'CMYK to sRGB color spaces', 'Fast processing'],
  },
  {
    id: 'svg-to-png',
    slug: 'svg-to-png',
    title: 'SVG to PNG Converter',
    shortDescription: 'Rasterize SVG vector illustrations into resolution-independent PNG images.',
    category: 'vector',
    categoryLabel: 'Vector Graphics',
    inputFormats: ['svg'],
    outputFormats: ['png', 'jpg', 'pdf'],
    status: 'supported',
    iconName: 'pen-tool',
    features: ['Vector rasterization', 'Custom width/height scaling', 'Transparent background retention'],
  },
  {
    id: 'xml-to-pdf',
    slug: 'xml-to-pdf',
    title: 'XML to PDF Converter',
    shortDescription: 'Render XML tree structures into formatted PDF documents.',
    category: 'data',
    categoryLabel: 'Data Files',
    inputFormats: ['xml'],
    outputFormats: ['pdf'],
    status: 'supported',
    iconName: 'database',
    features: ['Syntax tree formatting', 'Indent hierarchy preservation', 'Monospace font'],
  },

  // PDF Utility Tools
  {
    id: 'merge-pdf',
    slug: 'merge-pdf',
    title: 'Merge PDF Files',
    shortDescription: 'Combine multiple PDF documents into a single organized PDF file.',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    inputFormats: ['pdf'],
    outputFormats: ['pdf'],
    status: 'supported',
    popular: true,
    iconName: 'pdf',
    features: ['Multi-file reordering', 'Page sequence preservation', 'Fast stream concatenation'],
  },
  {
    id: 'split-pdf',
    slug: 'split-pdf',
    title: 'Split PDF Document',
    shortDescription: 'Extract specific pages or page ranges from a PDF into separate files.',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    inputFormats: ['pdf'],
    outputFormats: ['pdf'],
    status: 'supported',
    popular: true,
    iconName: 'pdf',
    features: ['Custom page ranges (e.g. 1-3, 5, 8)', 'Individual page extraction', 'ZIP bundle download'],
  },

  // Activated & New Specialized Converters
  {
    id: 'epub-to-pdf',
    slug: 'epub-to-pdf',
    title: 'EPUB to PDF Converter',
    shortDescription: 'Convert EPUB e-books to standard printable, paginated PDF books with clean chapter breaks.',
    category: 'ebooks',
    categoryLabel: 'Ebooks',
    inputFormats: ['epub'],
    outputFormats: ['pdf'],
    status: 'supported',
    popular: true,
    recentlyAdded: true,
    iconName: 'book',
    features: ['Chapter pagination', 'Font scaling', 'Table of contents preservation', 'Metadata retention'],
  },
  {
    id: 'heic-to-jpg',
    slug: 'heic-to-jpg',
    title: 'HEIC to JPG Converter',
    shortDescription: 'Convert Apple iPhone HEIC/HEIF photos to standard high-compatibility JPG & PNG images.',
    category: 'images',
    categoryLabel: 'Images',
    inputFormats: ['heic', 'heif'],
    outputFormats: ['jpg', 'png', 'webp'],
    status: 'supported',
    popular: true,
    recentlyAdded: true,
    iconName: 'image',
    features: ['Apple HEVC hardware decoding', 'EXIF metadata retention', 'Batch photo converter', 'Lossless PNG conversion'],
  },
  {
    id: 'pdf-to-docx',
    slug: 'pdf-to-docx',
    title: 'PDF to Word (DOCX)',
    shortDescription: 'Convert PDF files into editable Microsoft Word DOCX documents and formatted text.',
    category: 'documents',
    categoryLabel: 'Documents',
    inputFormats: ['pdf'],
    outputFormats: ['docx', 'txt'],
    status: 'supported',
    popular: true,
    recentlyAdded: true,
    iconName: 'file-text',
    features: ['Heading level detection', 'Paragraph restructuring', 'Editable Word OpenXML format', 'Page break preservation'],
  },
  {
    id: 'extract-zip',
    slug: 'extract-zip',
    title: 'ZIP Archive Inspector',
    shortDescription: 'Safely inspect, analyze file trees, and generate printable PDF inspection reports for ZIP archives.',
    category: 'archives',
    categoryLabel: 'Archives',
    inputFormats: ['zip'],
    outputFormats: ['pdf', 'txt'],
    status: 'supported',
    recentlyAdded: true,
    iconName: 'archive',
    features: ['File tree inspection', 'Compression ratio calculation', 'Printable PDF manifest', 'ZIP bomb safety protection'],
  },
  {
    id: 'md-to-docx',
    slug: 'md-to-docx',
    title: 'Markdown to Word (DOCX)',
    shortDescription: 'Convert Markdown (.md) documents to beautifully styled Microsoft Word DOCX files.',
    category: 'documents',
    categoryLabel: 'Documents',
    inputFormats: ['md', 'markdown'],
    outputFormats: ['docx', 'pdf'],
    status: 'supported',
    popular: true,
    recentlyAdded: true,
    iconName: 'file-text',
    features: ['Header typography styling', 'Bullet & numbered lists', 'Code block formatting', 'Bold/italic text runs'],
  },
  {
    id: 'txt-to-docx',
    slug: 'txt-to-docx',
    title: 'Text to Word (DOCX)',
    shortDescription: 'Transform plain text (.txt) and log files into formatted Microsoft Word DOCX documents.',
    category: 'text_code',
    categoryLabel: 'Text & Code',
    inputFormats: ['txt', 'log'],
    outputFormats: ['docx', 'pdf'],
    status: 'supported',
    recentlyAdded: true,
    iconName: 'code',
    features: ['Calibri 12pt styling', 'Automatic paragraph breaks', 'Clean line spacing', 'Instant download'],
  },
  {
    id: 'pdf-to-txt',
    slug: 'pdf-to-txt',
    title: 'PDF to Plain Text (TXT)',
    shortDescription: 'Extract raw text, notes, and strings from any PDF document into a clean .txt file.',
    category: 'pdf_tools',
    categoryLabel: 'PDF Tools',
    inputFormats: ['pdf'],
    outputFormats: ['txt'],
    status: 'supported',
    recentlyAdded: true,
    iconName: 'pdf',
    features: ['Full text extraction', 'Unicode character support', 'Multi-page concatenation', 'Fast download'],
  },
  {
    id: 'svg-to-webp',
    slug: 'svg-to-webp',
    title: 'SVG to WebP Modern Converter',
    shortDescription: 'Rasterize scalable vector graphics (SVG) into lightweight modern WebP images.',
    category: 'vector',
    categoryLabel: 'Vector Graphics',
    inputFormats: ['svg'],
    outputFormats: ['webp', 'png', 'jpg'],
    status: 'supported',
    popular: true,
    recentlyAdded: true,
    iconName: 'pen-tool',
    features: ['Modern WebP compression', 'Alpha transparency retention', 'Sharp vector rasterization', 'Fast download'],
  },
  {
    id: 'ico-to-png',
    slug: 'ico-to-png',
    title: 'Icon (ICO) to PNG Converter',
    shortDescription: 'Convert website favicons and application .ico files to standard high-resolution PNG images.',
    category: 'images',
    categoryLabel: 'Images',
    inputFormats: ['ico'],
    outputFormats: ['png', 'jpg', 'webp'],
    status: 'supported',
    recentlyAdded: true,
    iconName: 'image',
    features: ['Multi-resolution icon extraction', 'Alpha channel preservation', 'High-compatibility PNG output'],
  },
];
