import fs from 'fs/promises';
import path from 'path';
import PDFDocument from 'pdfkit';
import { ConversionEngine } from './ConversionEngine';
import { ConversionFile, ConversionResult, ValidationResult, OutputFormat, SupportedFormat } from '../types';
import { generateStorageFileName } from '../utils/idGenerator';
import { buildOutputDisplayName } from '../security/sanitize';
import { logger } from '../utils/logger';

export class DataConverter implements ConversionEngine {
  readonly name = 'DataConverter';

  readonly supportedInputMimeTypes = [
    'application/json',
    'text/csv',
    'text/tab-separated-values',
    'application/xml',
    'text/xml',
    'application/x-yaml',
    'text/yaml',
  ];

  readonly supportedInputExtensions = [
    'json', 'csv', 'tsv', 'xml', 'yaml', 'yml',
  ];

  readonly supportedOutputFormats: OutputFormat[] = ['pdf', 'jpg', 'png'];

  readonly maxFileSizeMB = 300;

  readonly supportedFormatsMeta: SupportedFormat[] = [
    { extension: 'json', mimeType: 'application/json', label: 'JSON Data', category: 'data', outputFormats: ['pdf', 'jpg', 'png'] },
    { extension: 'csv', mimeType: 'text/csv', label: 'CSV Spreadsheet Data', category: 'data', outputFormats: ['pdf', 'jpg', 'png'] },
    { extension: 'tsv', mimeType: 'text/tab-separated-values', label: 'TSV Tabbed Data', category: 'data', outputFormats: ['pdf', 'jpg', 'png'] },
    { extension: 'xml', mimeType: 'application/xml', label: 'XML Structured Data', category: 'data', outputFormats: ['pdf', 'jpg', 'png'] },
    { extension: 'yaml', mimeType: 'application/x-yaml', label: 'YAML Configuration', category: 'data', outputFormats: ['pdf', 'jpg', 'png'] },
  ];

  async validate(file: ConversionFile): Promise<ValidationResult> {
    try {
      const content = await fs.readFile(file.metadata.storagePath, 'utf-8');
      if (!content || content.trim().length === 0) {
        return { valid: false, errorMessage: 'File is empty' };
      }
      return { valid: true };
    } catch {
      return { valid: false, errorMessage: 'Could not read data file' };
    }
  }

  async convert(file: ConversionFile, outputDir: string): Promise<ConversionResult> {
    const startTime = Date.now();
    const { outputFormat } = file;
    const inputPath = file.metadata.storagePath;

    try {
      const rawText = await fs.readFile(inputPath, 'utf-8');
      
      // Formatted data representation
      let displayLines: string[] = [];
      const ext = file.metadata.extension.toLowerCase();

      if (ext === 'json') {
        try {
          const parsed = JSON.parse(rawText);
          displayLines = JSON.stringify(parsed, null, 2).split('\n');
        } catch {
          displayLines = rawText.split('\n');
        }
      } else {
        displayLines = rawText.split('\n');
      }

      const storageName = generateStorageFileName('pdf');
      const outputPath = path.join(outputDir, storageName);
      const outputName = buildOutputDisplayName(file.metadata.originalName, 'pdf');

      await new Promise<void>((resolve, reject) => {
        const doc = new PDFDocument({ margin: 40, size: 'A4', info: { Title: outputName } });
        const stream = require('fs').createWriteStream(outputPath);
        doc.pipe(stream);

        // Header
        doc.fontSize(16).fillColor('#1e293b').text(file.metadata.originalName, { align: 'left' });
        doc.fontSize(9).fillColor('#64748b').text(`Data View • ${displayLines.length} lines • Generated by ConvertX`);
        doc.moveDown(1);
        doc.lineWidth(1).strokeColor('#cbd5e1').moveTo(40, doc.y).lineTo(555, doc.y).stroke();
        doc.moveDown(1);

        doc.font('Courier').fontSize(9).fillColor('#0f172a');

        const maxLinesPerPage = 55;
        let lineCount = 0;

        for (const line of displayLines) {
          if (lineCount > 0 && lineCount % maxLinesPerPage === 0) {
            doc.addPage();
            doc.font('Courier').fontSize(9).fillColor('#0f172a');
          }
          // Truncate ultra-long lines to avoid overflow
          const safeLine = line.length > 120 ? line.substring(0, 117) + '...' : line;
          doc.text(safeLine);
          lineCount++;
        }

        doc.end();
        stream.on('finish', resolve);
        stream.on('error', reject);
      });

      const stat = await fs.stat(outputPath);
      return {
        success: true,
        outputPath,
        outputName,
        sizeBytes: stat.size,
        pageCount: Math.ceil(displayLines.length / 55) || 1,
        conversionTimeMs: Date.now() - startTime,
      };
    } catch (err) {
      logger.error(`DataConverter failed: ${err}`);
      throw new Error(`Data conversion failed: ${err instanceof Error ? err.message : 'Unknown error'}`);
    }
  }
}
